//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyFinance2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FamilyFinance2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id,
        ///	   CASE WHEN Account.creditDebit = 0 THEN lSum.credit - lSum.debit ELSE lSum.debit - lSum.credit END 
        ///FROM Account INNER JOIN (
        ///	SELECT accountID, 
        ///		   SUM(CASE WHEN LineItem.creditDebit = 0 THEN LineItem.amount ELSE 0 END) AS credit, 
        ///		   SUM(CASE WHEN LineItem.creditDebit = 1 THEN LineItem.amount ELSE 0 END) AS debit
        ///	FROM LineItem 
        ///	WHERE accountID IN (SELECT id FROM Account WHERE catagory = @@ )
        ///	GROUP BY accountID ) AS lSum ON Account.id = lSum.accountID
        ///WHERE lSum.credit &lt;&gt; lSum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccountBalances {
            get {
                return ResourceManager.GetString("AccountBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id, name, envelopes
        ///FROM Account
        ///WHERE id &gt; 0 AND closed = 0 AND catagory = @@
        ///ORDER BY name;
        ///--@ 1 AND typeID = 12
        ///--@ 3
        ///--@ 2 
        ///
        ///.
        /// </summary>
        internal static string AccountDetails {
            get {
                return ResourceManager.GetString("AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT catagory, typeID, id
        ///FROM Account
        ///WHERE id IN 
        ///(
        ///-- Find the accounts where credits and debits don&apos;t add up within the transactions
        ///SELECT DISTINCT LineItem.accountID
        ///FROM LineItem
        ///WHERE transactionID IN (
        ///	SELECT transactionID
        ///	FROM (
        ///		SELECT transactionID, 
        ///			   SUM(CASE WHEN LineItem.creditDebit = 0 THEN LineItem.amount ELSE 0 END) AS credit, 
        ///			   SUM(CASE WHEN LineItem.creditDebit = 1 THEN LineItem.amount ELSE 0 END) AS debit
        ///		FROM LineItem 
        ///		WHERE accountID &lt;&gt; oppAccountID
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccountErrors {
            get {
                return ResourceManager.GetString("AccountErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CASE WHEN Account.creditDebit = 0 THEN lSum.credit - lSum.debit ELSE lSum.debit - lSum.credit END 
        ///FROM Account INNER JOIN (
        ///	SELECT accountID, 
        ///		   SUM(CASE WHEN LineItem.creditDebit = 0 THEN LineItem.amount ELSE 0 END) AS credit, 
        ///		   SUM(CASE WHEN LineItem.creditDebit = 1 THEN LineItem.amount ELSE 0 END) AS debit
        ///	FROM LineItem 
        ///	WHERE accountID = @@ 
        ///	GROUP BY accountID ) AS lSum ON Account.id = lSum.accountID
        ///WHERE lSum.credit &lt;&gt; lSum.debit;
        ///
        ///--@  1
        ///--@.
        /// </summary>
        internal static string AccountSingleBalance {
            get {
                return ResourceManager.GetString("AccountSingleBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT AccountType.id, AccountType.name
        ///FROM AccountType INNER JOIN Account ON AccountType.id = Account.typeID
        ///WHERE Account.closed = 0 AND Account.catagory = @@
        ///ORDER BY AccountType.name;
        ///--@ 1
        ///--@ 2
        ///--@ 3.
        /// </summary>
        internal static string AccountTypes {
            get {
                return ResourceManager.GetString("AccountTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT eSum.credit - eSum.debit
        ///FROM (
        ///	SELECT SUM(CASE WHEN LineItem.creditDebit = 0 THEN EnvelopeLine.amount ELSE 0 END) AS credit, 
        ///		   SUM(CASE WHEN LineItem.creditDebit = 1 THEN EnvelopeLine.amount ELSE 0 END) AS debit
        ///	FROM LineItem INNER JOIN EnvelopeLine ON LineItem.id = EnvelopeLine.lineItemID
        ///	WHERE EnvelopeLine.envelopeID = @@
        ///	GROUP BY EnvelopeLine.envelopeID ) AS eSum;
        ///
        ///--@ 52
        ///--@ 52 AND LineItem.accountID == 23.
        /// </summary>
        internal static string AEBalance {
            get {
                return ResourceManager.GetString("AEBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT elSum.debit - elSum.credit
        ///FROM (
        ///	SELECT  EnvelopeLine.envelopeID, 
        ///			SUM(CASE WHEN LineItem.creditDebit = 0 THEN EnvelopeLine.amount ELSE 0 END) AS credit, 
        ///			SUM(CASE WHEN LineItem.creditDebit = 1 THEN EnvelopeLine.amount ELSE 0 END) AS debit
        ///	FROM LineItem INNER JOIN EnvelopeLine ON LineItem.id = EnvelopeLine.lineItemID
        ///	WHERE LineItem.accountID = @aID AND EnvelopeLine.envelopeID = @eID
        ///	GROUP BY EnvelopeLine.envelopeID )  AS elSum
        ///
        ///--@ 3.
        /// </summary>
        internal static string AESingleBalance {
            get {
                return ResourceManager.GetString("AESingleBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------------------------------------------------------
        ///-------------------------------------------------------------------------------
        ///CREATE TABLE AccountType
        ///(
        ///	id					int				NOT NULL,
        ///	[name]				nvarchar(30)	NOT NULL,
        ///	CONSTRAINT PK_AccountType_id        PRIMARY KEY (id)
        ///);
        ///INSERT INTO AccountType VALUES (-1, &apos; &apos;); -- Null Account Type
        ///
        ///
        ///-------------------------------------------------------------------------------
        ///---------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BuildTables {
            get {
                return ResourceManager.GetString("BuildTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SUM(cnt)
        ///FROM 
        ///(
        ///-- Find the accounts where credits and debits don&apos;t add up within the transactions
        ///SELECT COUNT(1) AS cnt
        ///FROM LineItem
        ///WHERE accountID = @@ AND transactionID IN (
        ///	SELECT transactionID
        ///	FROM (
        ///		SELECT transactionID, 
        ///			   SUM(CASE WHEN LineItem.creditDebit = 0 THEN LineItem.amount ELSE 0 END) AS credit, 
        ///			   SUM(CASE WHEN LineItem.creditDebit = 1 THEN LineItem.amount ELSE 0 END) AS debit
        ///		FROM LineItem 
        ///		WHERE accountID &lt;&gt; oppAccountID 
        ///		GROUP BY transactionID ) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CountAccountErrors {
            get {
                return ResourceManager.GetString("CountAccountErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(1)
        ///FROM LineItem INNER JOIN EnvelopeLine ON LineItem.id = EnvelopeLine.lineitemID
        ///WHERE LineItem.accountID = @@
        ///
        ///--@ 3.
        /// </summary>
        internal static string CountELines {
            get {
                return ResourceManager.GetString("CountELines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Delete the orphaned EnvelopeLines
        ///DELETE FROM EnvelopeLine
        ///WHERE lineItemID IN 
        ///	(SELECT LineItem.id 
        ///	 FROM LineItem INNER JOIN Account ON LineItem.accountID = Account.id 
        ///	 WHERE Account.envelopes = 0);
        ///	 
        ///-- Set all the LineItems.envelopeId to NULL
        ///UPDATE LineItem
        ///SET envelopeID = -1
        ///WHERE accountID IN (SELECT id FROM Account WHERE envelopes = 0);.
        /// </summary>
        internal static string DeleteOrphanELines {
            get {
                return ResourceManager.GetString("DeleteOrphanELines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE EnvelopeLine;
        ///DROP TABLE LineItem;
        ///DROP TABLE Envelope;
        ///DROP TABLE Account;
        ///DROP TABLE LineType;
        ///DROP TABLE EnvelopeGroup;
        ///DROP TABLE AccountType;
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string DropTables {
            get {
                return ResourceManager.GetString("DropTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT envelopeID, eSum.debit - eSum.credit
        ///FROM (
        ///	SELECT EnvelopeLine.envelopeID,
        ///		   SUM(CASE WHEN LineItem.creditDebit = 0 THEN EnvelopeLine.amount ELSE 0 END) AS credit, 
        ///		   SUM(CASE WHEN LineItem.creditDebit = 1 THEN EnvelopeLine.amount ELSE 0 END) AS debit
        ///	FROM LineItem INNER JOIN EnvelopeLine ON LineItem.id = EnvelopeLine.lineItemID
        ///	WHERE EnvelopeLine.envelopeID IN (SELECT id FROM Envelope WHERE closed = 0  @@)
        ///	GROUP BY EnvelopeLine.envelopeID ) AS eSum;
        ///
        ///--@ AND groupID = 4
        ///--@.
        /// </summary>
        internal static string EnvelopeBalances {
            get {
                return ResourceManager.GetString("EnvelopeBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT EnvelopeGroup.id, EnvelopeGroup.name
        ///FROM EnvelopeGroup INNER JOIN Envelope ON EnvelopeGroup.id = Envelope.groupID
        ///WHERE Envelope.closed = 0 AND Envelope.id &gt; 0
        ///ORDER BY EnvelopeGroup.name;
        ///.
        /// </summary>
        internal static string EnvelopeGroups {
            get {
                return ResourceManager.GetString("EnvelopeGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id, name
        ///FROM Envelope
        ///WHERE id &gt; 0 AND closed = 0 @@
        ///ORDER BY name;
        ///
        ///--@ AND groupID = 5
        ///--@
        ///.
        /// </summary>
        internal static string EnvelopeNames {
            get {
                return ResourceManager.GetString("EnvelopeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT eSum.debit - eSum.credit
        ///FROM (
        ///	SELECT EnvelopeLine.envelopeID,
        ///		   SUM(CASE WHEN LineItem.creditDebit = 0 THEN EnvelopeLine.amount ELSE 0 END) AS credit, 
        ///		   SUM(CASE WHEN LineItem.creditDebit = 1 THEN EnvelopeLine.amount ELSE 0 END) AS debit
        ///	FROM LineItem INNER JOIN EnvelopeLine ON LineItem.id = EnvelopeLine.lineItemID
        ///	WHERE EnvelopeLine.envelopeID = @@
        ///	GROUP BY EnvelopeLine.envelopeID ) AS eSum;
        ///
        ///--@  1
        ///--@.
        /// </summary>
        internal static string EnvelopeSingleBalance {
            get {
                return ResourceManager.GetString("EnvelopeSingleBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Find the Lines where the EnvelopeLines don&apos;t add up to the lines amount
        ///SELECT id
        ///FROM LineItem INNER JOIN (
        ///	SELECT lineItemID, 
        ///		   SUM(amount) AS amount 
        ///	FROM EnvelopeLine 
        ///	GROUP BY lineItemID) AS eSum ON LineItem.id = eSum.lineItemID
        ///WHERE LineItem.amount &lt;&gt; eSum.amount AND LineItem.accountID = @@
        ///
        ///UNION ALL
        ///
        ///--Find the accounts where the lines should have subLines
        ///SELECT id
        ///FROM LineItem
        ///WHERE accountID IN (SELECT id FROM Account WHERE envelopes = 1 AND ID = @@) 
        ///	  AND id NOT IN ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LineEnvelopeLineErrors {
            get {
                return ResourceManager.GetString("LineEnvelopeLineErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT LineItem.id
        ///FROM LineItem
        ///WHERE accountID = @@ AND transactionID IN (
        ///	SELECT transactionID
        ///	FROM (
        ///		SELECT transactionID, 
        ///			   SUM(CASE WHEN LineItem.creditDebit = 0 THEN LineItem.amount ELSE 0 END) AS credit, 
        ///			   SUM(CASE WHEN LineItem.creditDebit = 1 THEN LineItem.amount ELSE 0 END) AS debit
        ///		FROM LineItem 
        ///		WHERE accountID &lt;&gt; oppAccountID 
        ///		GROUP BY transactionID ) AS TSums
        ///	WHERE credit &lt;&gt; debit)
        ///
        ///--@ 3
        ///.
        /// </summary>
        internal static string LineTransactionErrors {
            get {
                return ResourceManager.GetString("LineTransactionErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Account
        ///SET envelopes = 1
        ///WHERE id in (
        ///SELECT DISTINCT accountID 
        ///FROM LineItem 
        ///WHERE id IN (
        ///	SELECT DISTINCT LineItemID
        ///	FROM EnvelopeLine ) )
        ///.
        /// </summary>
        internal static string SetAccountEnvelopes {
            get {
                return ResourceManager.GetString("SetAccountEnvelopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Envelope.id, Envelope.name, (elSum.debit - elSum.credit) AS balance
        ///FROM Envelope INNER JOIN (
        ///	SELECT  EnvelopeLine.envelopeID, 
        ///			SUM(CASE WHEN LineItem.creditDebit = 0 THEN EnvelopeLine.amount ELSE 0 END) AS credit, 
        ///			SUM(CASE WHEN LineItem.creditDebit = 1 THEN EnvelopeLine.amount ELSE 0 END) AS debit
        ///	FROM LineItem INNER JOIN EnvelopeLine ON LineItem.id = EnvelopeLine.lineItemID
        ///	WHERE LineItem.accountID = @@
        ///	GROUP BY EnvelopeLine.envelopeID ) AS elSum ON Envelope.id = elSum.envelopeID [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SubAccountBalances {
            get {
                return ResourceManager.GetString("SubAccountBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Account.id, Account.name, (elSum.debit - elSum.credit) AS balance
        ///FROM Account INNER JOIN (
        ///	SELECT  LineItem.accountID, 
        ///			SUM(CASE WHEN LineItem.creditDebit = 0 THEN EnvelopeLine.amount ELSE 0 END) AS credit, 
        ///			SUM(CASE WHEN LineItem.creditDebit = 1 THEN EnvelopeLine.amount ELSE 0 END) AS debit
        ///	FROM LineItem INNER JOIN EnvelopeLine ON LineItem.id = EnvelopeLine.lineItemID
        ///	WHERE EnvelopeLine.envelopeID = @@
        ///	GROUP BY LineItem.accountID ) AS elSum ON Account.id = elSum.accountID
        ///WHERE Ac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SubEnvelopeBalances {
            get {
                return ResourceManager.GetString("SubEnvelopeBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///-------------------------------------------------------------------------------
        ///-------------------------------------------------------------------------------
        ///--TABLE (id, name(30), typeID, catagory(1), closed(b), creditDebit(b), envelopes(b))
        ///INSERT INTO Account VALUES (101, &apos;Main Checking&apos;, 4, 2, 0, 1, 1);
        ///INSERT INTO Account VALUES (102, &apos;Vacation Savings&apos;, 5, 2, 0, 1, 1);
        ///INSERT INTO Account VALUES (103, &apos;Local Bank MC&apos;, 6, 2, 0, 0, 1);
        ///INSERT INTO Account VALUES (104, &apos;Car Loan&apos;, 3, 2, 0, 0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData {
            get {
                return ResourceManager.GetString("TestData", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap TLVBank {
            get {
                object obj = ResourceManager.GetObject("TLVBank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TLVBankAndFlag {
            get {
                object obj = ResourceManager.GetObject("TLVBankAndFlag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TLVEnvelope {
            get {
                object obj = ResourceManager.GetObject("TLVEnvelope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TLVMoney {
            get {
                object obj = ResourceManager.GetObject("TLVMoney", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TLVRedBank {
            get {
                object obj = ResourceManager.GetObject("TLVRedBank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TLVRedEnvelope {
            get {
                object obj = ResourceManager.GetObject("TLVRedEnvelope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TLVRedFlag {
            get {
                object obj = ResourceManager.GetObject("TLVRedFlag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
